### ISSUE TITLE
Many error messages appear in the CMD window

### ISSUE THREAD

**Issue by LRF520** [xiaopengli89/precord#9] opened 2022-09-06 09:14 UTC
I suddenly have a few questions to ask. Thank you:

(1) Many error messages appear in the CMD window;

(2) If the system has multiple GPUs, how is the GPU usage calculated?

(3) Which CPUs and GPUs does precord support for windows? (such as Intel, AMD and NVIDIA)

(4) Which CPUs and GPUs does precord support for MacOS systems? (such as Intel, AMD, NVIDIA, M1)

![20220906_170505](https://user-images.githubusercontent.com/58470642/188596655-eb24bdc2-67a2-4f68-bbbb-dd80015e9294.jpg)

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ferrisetw-0.1.1\src\schema.rs:110:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ferrisetw-0.1.1\src\schema.rs:110:54thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ferrisetw-0.1.1\src\schema.rs:110:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ferrisetw-0.1.1\src\schema.rs:110:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ferrisetw-0.1.1\src\schema.rs:110:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by xiaopengli89** [comment] 2022-09-06 16:40
1. Recording fps or net needs to be run as administrator.
2. precord will take the value of the gpu with the highest usage, which is consistent with the task manager of windows, e.g. process A uses 10% of GPU0, 20% of GPU1, and the final value is 20%
3. All cpus and gpus
4. All cpus and gpus

**Comment by LRF520** [comment] 2022-09-07 02:15
> 1. Recording fps or net needs to be run as administrator.
> 2. precord will take the value of the gpu with the highest usage, which is consistent with the task manager of windows, e.g. process A uses 10% of GPU0, 20% of GPU1, and the final value is 20%
> 3. All cpus and gpus
> 4. All cpus and gpus

> 1. I had recorded fps or net  as administrator,but also many error messages appear in the CMD window,i think the precord of windows is not very stable and may need to be optimized.

**Comment by xiaopengli89** [comment] 2022-09-07 03:34
> I had recorded fps or net as administrator,but also many error messages appear in the CMD window,i think the precord of windows is not very stable and may need to be optimized.

Please provide your operating system version and operating procedure, I will try to reproduce the problem.

> I think it is necessary to list the usage data of each GPU separately, because each GPU has its own value. Complex scenarios need to refer to the usage of each GPU. Moreover, each GPU has its own independent memory data, which is a unique feature of GPU and is obviously different from CPU. It is also important to add the monitoring function of GPU memory data, because GPU can also have fatal problems of memory overflow.

I understand what you mean, but this is not the goal of precord, you need more professional analysis tools.

**Comment by LRF520** [comment] 2022-09-07 06:09
> > I had recorded fps or net as administrator,but also many error messages appear in the CMD window,i think the precord of windows is not very stable and may need to be optimized.
> 
> Please provide your operating system version and operating procedure, I will try to reproduce the problem.
> 
> > I think it is necessary to list the usage data of each GPU separately, because each GPU has its own value. Complex scenarios need to refer to the usage of each GPU. Moreover, each GPU has its own independent memory data, which is a unique feature of GPU and is obviously different from CPU. It is also important to add the monitoring function of GPU memory data, because GPU can also have fatal problems of memory overflow.
> 
> I understand what you mean, but this is not the goal of precord, you need more professional analysis tools.


This problem often occurs when I execute Python commands in the CMD window and run the commands for a long time. However, I have tried two win10 systems, and this error will occur, so I think it may not have much to do with the win10 version.

![20220907_140512](https://user-images.githubusercontent.com/58470642/188801355-d8b3d91d-913f-4cfd-abd0-6bded5144456.jpg)

![20220907_140550](https://user-images.githubusercontent.com/58470642/188801382-2e234c33-9fe5-42b1-aa4e-aded878144cb.jpg)

![image](https://user-images.githubusercontent.com/58470642/188801419-03e3df1a-d37d-47aa-adc8-5956da1a6d3e.png)

**Comment by xiaopengli89** [comment] 2022-09-07 06:32
The problem is caused by upstream dependencies.

**Comment by xiaopengli89** [comment] 2022-09-08 07:02
Please try version v0.5.12-etw-fix~

**Comment by LRF520** [comment] 2022-09-08 07:14
> Please try version v0.5.12-etw-fix~

Still have to work hard~~~

![image](https://user-images.githubusercontent.com/58470642/189058634-36cf0362-3184-4728-8bcf-a9dedec222a5.png)

thread 'main' panicked at 'No such process(288)', src\types.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'No such process(18784)', src\types.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'No such process(15572)', src\types.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ferrisetw-0.1.1\src\schema.rs:110:54

**Comment by xiaopengli89** [comment] 2022-09-08 07:45
How did you run precord, from the command line or python?

**Comment by LRF520** [comment] 2022-09-08 07:49
> How did you run precord, from the command line or python?

Run python file on cmd window for a long time:

![20220907_140512](https://user-images.githubusercontent.com/58470642/188801355-d8b3d91d-913f-4cfd-abd0-6bded5144456.jpg)

![20220907_140550](https://user-images.githubusercontent.com/58470642/188801382-2e234c33-9fe5-42b1-aa4e-aded878144cb.jpg)

**Comment by xiaopengli89** [comment] 2022-09-08 08:08
I will try to run this script next week, I don't have windows at the moment, thanks for your feedback~ :+1:

**Comment by LRF520** [comment] 2022-09-08 08:13
> I will try to run this script next week, I don't have windows at the moment, thanks for your feedback~ 👍



It is easier to use "--name - Name of processes" to reproduce this problem. I think it is caused by the appearance or disappearance of the temporary process PID in the process name.

**Comment by xiaopengli89** [comment] 2022-09-13 06:16
Please try version v0.6.0, I executed your script for 20 minutes without exception.

**Comment by LRF520** [comment] 2022-09-13 10:41
> Please try version v0.6.0, I executed your script for 20 minutes without exception.



This is what I did:

Run the python script in the CMD window, monitor a browser name repeatedly, and then I keep opening many browser pages, and then I keep closing all browser pages. I do it for so many times,this error will occur !

![image](https://user-images.githubusercontent.com/58470642/189879876-d33854ed-7650-4e3d-957e-25781036e0b5.png)

![image](https://user-images.githubusercontent.com/58470642/189880075-6ccf9d44-68d6-4dd6-afc9-0ecc3b268cfa.png)

![image](https://user-images.githubusercontent.com/58470642/189880436-c4dc6b31-ef0e-4a56-9847-592289dab07e.png)

import os

while True:
    print(os.popen(r"C:\Users\EDZ\Desktop\Precord\precord.exe --name 360chrome.exe -c fps -n 1").read())

**Comment by xiaopengli89** [comment] 2022-09-13 13:44
When you end a recording, you need to sleep for a while and let the operating system recycle the counter.

**Comment by xiaopengli89** [comment] 2022-09-13 13:50
Maybe we can solve this by creating a new random counter each time, but I'm not sure if that's the right thing to do.

**Comment by LRF520** [comment] 2022-09-13 15:30
> Here is my script:
> 
> ```python
> import os
> 
> print(os.popen(r".\precord.exe --name chrome -c fps --time 20m").read())
> ```

According to long-term observation, in fact, I think this error will not affect real data collection. It may only be caused by precord's exception handling mechanism, but ordinary people can't understand this error prompt.

**Comment by xiaopengli89** [comment] 2022-09-14 05:55
> According to long-term observation, in fact, I think this error will not affect real data collection. It may only be caused by precord's exception handling mechanism, but ordinary people can't understand this error prompt.

We can't handle this exception, it's caused by n4r1b/ferrisetw#26.

**Comment by LRF520** [comment] 2022-09-14 08:27
> > According to long-term observation, in fact, I think this error will not affect real data collection. It may only be caused by precord's exception handling mechanism, but ordinary people can't understand this error prompt.
> 
> We can't handle this exception, it's caused by [n4r1b/ferrisetw#26](https://github.com/n4r1b/ferrisetw/issues/26).

By this time, I can no longer evaluate the impact of this error. I think if it does not affect the continuous collection of data, we can not pay too much attention to it for the time being.

**Comment by xiaopengli89** [comment] 2023-01-15 07:33
This issue should be fixed by [2b85f3d](https://github.com/xiaopengli89/precord/commit/2b85f3ddeb83d21bfad0fe8f4fbde4e9911ad661).

**Comment by xiaopengli89** [comment] 2023-01-16 06:46
Fixed by v0.7.4.

**Closed by xiaopengli89** 2023-01-16 06:46 UTC
Labels: bug
